# Generated by Django 4.1.7 on 2023-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
