# Generated by Django 4.1.7 on 2023-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_selected_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
