# Generated by Django 4.1.7 on 2023-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected',
            name='applied',
            field=models.DateTimeField(),
        ),
    ]
